# spring:
#     application:
#         name: personapi
#     profiles:
#         active: dev
#     datasource:
#         driverClassname: com.mysql.cj.jdbc.Driver
#         url: jdbc:mysql://127.0.0.1:3308/curso_java?useTimezone=true&serverTimezone=UTC
#         username: root
#         password: admin123
#     jpa:
#         ahow-sql: false 
#         dialect: org.hibernate.MySQL8Dialect
#         hibernate:
#             ddl-auto: update

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/curso_java?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
    driverClassName: com.mysql.cj.jdbc.Driver